config/routes.rb
Rails.application.routes.draw do
  root 'gossip#index'

  resources :gossip do
    resources :comments, shallow: true do
      resources :comments, defaults: { commentable: 'comment' }
      resources :likes, only: [:create, :destroy], defaults: { likeable: 'comment' }
    end
    resources :likes, only: [:create, :destroy], defaults: { likeable: 'gossip' }
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :tags

  resources :users
  resources :cities, only: :show

  get '/contacts', to: 'static#contacts'
  get '/team', to: 'static#team'
  get '/welcome/:name', to: 'static#welcome'

  post '/update_location', to: 'users#update_location'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user

  belongs_to :commentable, polymorphic: true
  has_many :likes, as: :likeable
  has_many :comments, as: :commentable
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  after_create :set_location
  attr_accessor :tag_ids

  validates :title, presence: true, length: { in: 2..14 }
  validates :content, presence: true
  validates :latitude, numericality: { greater_than_or_equal_to: -90, less_than_or_equal_to: 90 }, allow_nil: true
  validates :longitude, numericality: { greater_than_or_equal_to: -180, less_than_or_equal_to: 180 }, allow_nil: true

  belongs_to :user

  has_many :gossip_tags
  has_many :tags, through: :gossip_tags

  has_many :comments, as: :commentable

  has_many :likes, as: :likeable

  def set_location
    self.longitude = user.longitude
    self.latitude = user.latitude
    save!
  end
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likeable, polymorphic: true
end

app/models/message_recipient.rb
class MessageRecipient < ApplicationRecord
  belongs_to :private_message
  belongs_to :recipient, class_name: 'User'
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  has_many :message_recipients
  has_many :recipients, through: :message_recipients
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :title, presence: true
  has_many :gossip_tags
  has_many :gossips, through: :gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true
  validates_format_of :email, with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "must be a valid email address"
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :city, presence: true
  validates :age, presence: true
  validates :description, presence: true
  validates :latitude, numericality: { greater_than_or_equal_to: -90, less_than_or_equal_to: 90 }, allow_nil: true
  validates :longitude, numericality: { greater_than_or_equal_to: -180, less_than_or_equal_to: 180 }, allow_nil: true

  belongs_to :city
  has_many :gossips

  has_many :sent_messages, class_name: 'PrivateMessage', foreign_key: 'sender_id'
  has_many :message_recipients, foreign_key: :recipient_id
  has_many :received_messages, through: :message_recipients, source: :private_message

  has_many :comments

  has_many :likes
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user
  before_action :set_commentable, only: [:create]

  def create
    @comment = Comment.new(
      commentable: @commentable,
      user: current_user,
      content: params[:comment][:content]
    )
    if @comment.save
      flash[:notice] = 'Comment creation successful'
    else
      flash.now[:alert] = error_string(@comment)
    end
    redirect_to gossip_path(root_gossip_id(@comment))
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    if check_if_current_user(@comment.user) && @comment.update(content: params[:comment][:content])
      flash[:notice] = 'Comment update successful'
      redirect_to gossip_path(root_gossip_id(@comment))
    else
      flash.now[:alert] = error_string(@comment)
      render :edit
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    root_gossip_id = root_gossip_id(@comment)
    if check_if_current_user(@comment.user) && @comment.destroy
      flash[:notice] = 'Comment deleted successfully'
    else
      flash.now[:alert] = error_string(@comment)
    end
    redirect_to gossip_path(root_gossip_id)
  end

  private

  def set_commentable
    if params.key?(:gossip_id)
      @commentable = Gossip.find(params[:gossip_id])
    else
      @commentable = Comment.find(params[:comment_id])
    end
  end

  def root_gossip_id(comment)
    comment.commentable.instance_of?(Gossip) ? comment.commentable.id : comment.commentable.commentable.id
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user
  before_action :set_likeable, only: [:create]

  def create
    @like = @likeable.likes.new(user: current_user)
    flash[:alert] = error_string(@like) unless @like.save
    redirect_back_or_to gossip_path(root_gossip_id(@like))
  end

  def destroy
    @like = Like.find(params[:id])

    flash[:alert] = error_string(@like) unless @like.destroy

    redirect_back_or_to gossip_path(root_gossip_id(@like))
  end

  private

  def root_gossip_id(like)
    like.likeable.instance_of?(Gossip) ? like.likeable.id : like.likeable.commentable.id
  end

  def set_likeable
    @likeable = params[:likeable].classify.constantize.find(params[:like][:likeable_id])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
    @gossips = @tag.gossips
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def random_card_class
    ['card-bg-1', 'card-bg-2', 'card-bg-3', 'card-bg-4', 'card-bg-5'].sample
  end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/geolocation_helper.rb
# frozen_string_literal: true

module GeolocationHelper
  def within_50_meters?(point1, point2)
    if point1.latitude && point1.longitude && point2.latitude && point2.longitude
      lat1 = point1.latitude
      lon1 = point1.longitude
      lat2 = point2.latitude
      lon2 = point2.longitude

      radius_of_earth = 6371e3
      latitude1_rad = lat1 * Math::PI / 180
      latitude2_rad = lat2 * Math::PI / 180
      change_in_latitude_rad = (lat2 - lat1) * Math::PI / 180
      change_in_longitude_rad = (lon2 - lon1) * Math::PI / 180

      a = Math.sin(change_in_latitude_rad / 2)**2 +
          Math.cos(latitude1_rad) * Math.cos(latitude2_rad) *
          Math.sin(change_in_longitude_rad / 2)**2
      c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a))

      distance = radius_of_earth * c

      distance <= 50
    else
      false
    end
  end
end

app/helpers/gossip_helper.rb
module GossipHelper
  include GeolocationHelper
  def nearby_gossip
    Gossip.all.filter { |gossip| within_50_meters?(gossip, current_user) }
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def check_if_current_user(user)
    user == current_user
  end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment_likes.html.erb
<div id="comment-likes" class="container d-flex flex-row m-2 justify-content-end">
  <% if comment.likes.map(&:user).include?(current_user) %>
    <% like = comment.likes.find_by(user: current_user) %>
    <%= form_with(model: like, url: like_path(like), method: :delete, local: true) do |form| %>
      <button name="commit" type="submit" class="btn btn-success position-relative">
        Remove Like <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill badge bg-secondary"><%= comment.likes.count %></span>
      </button>
    <% end %>

  <% else %>
    <%= form_with(model: Like.new , url: comment_likes_path(comment), local: true) do |form| %>
      <%= form.hidden_field :likeable_id, value: comment.id %>
      <button name="commit" type="submit" class="btn btn-success position-relative">
        Like <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill badge bg-secondary"><%= comment.likes.count %></span>
      </button>
    <% end %>
  <% end %>
</div>

app/views/comments/_comment_on_comments_index.html.erb
<% if comment.comments.count > 0 %>
  
  <button 
    type="button" 
    class="btn btn-dark m-1"
    data-bs-toggle="collapse"
    data-bs-target="#comment-on-comments-index"
    aria-expanded="false"
    aria-controls="comment-on-comments-index">
    Show all <%= comment.comments.count %> comments
    </button>
<% end %>
<div id="comment-on-comments-index" class="container mt-2 collapse">
  <% comment.comments.each do |comment| %>
    <h5>By: <%= comment.user.first_name %></h5>
    <p><%= comment.content %></p>
    <% if check_if_current_user(comment.user) %>

      <div class="d-flex justify-content-center">
        <%= button_to "Edit comment",
          edit_comment_path(
            id: comment.id
          ),
          method: :get,
          class: "btn btn-warning mx-2"
        %>

        <%= button_to "Delete comment",
          comment_path(
            id: comment.id
          ),
          method: :delete,
          class: "btn btn-danger mx-2"
        %>
      </div>
    <% end %>
    <hr>
  <% end %>
</div>

app/views/comments/_comment_on_comments_new.html.erb
<button 
  type="button" 
  class="btn btn-dark m-1"
  data-bs-toggle="collapse"
  data-bs-target="#comment-on-comments-new"
  aria-expanded="false"
  aria-controls="comment-on-comments-new">
  Write a comment
</button>
<div id="comment-on-comments-new" class="container collapse">
  <div class="container m-2">
    <div class="d-flex flex-column">
      <%= form_with(model: Comment.new, url: comment_comments_path(comment), local: true) do |form| %>
        <%= form.hidden_field :comment_id, value: comment.id %>
        <%= form.label "Write your comment:", class: "form-label" %>
        <br>
        <%= form.text_area :content, class: "form-control" %>
        <br>
        <%= form.submit "Post", class:"btn btn-dark" %>
      <% end %>
    </div>
  </div>
</div>

app/views/comments/_comments_index.html.erb
<div id="comments-index">
  
  <% gossip.comments.each do |comment| %>
    <div class="p-2 card <%= ['card-bg-1', 'card-bg-2', 'card-bg-3', 'card-bg-4', 'card-bg-5'].sample %> d-flex flex-wrap m-1">
      <div class="card-body w-30">
        <div class="d-flex flex-column">
          <h5 class="card-title">By: <%= comment.user.first_name %></h5>
          <p class="card-text"><%= comment.content %></p>
          <% if check_if_current_user(comment.user) %>

            <div class="d-flex justify-content-center">
              <%= button_to "Edit comment",
                edit_comment_path(
                  id: comment.id
                ),
                method: :get,
                class: "btn btn-warning mx-2"
              %>

            <%= button_to "Delete comment",
              comment_path(
                id: comment.id
              ),
              method: :delete,
              class: "btn btn-danger mx-2"
            %>
          </div>
        <% end %>
        <%= render partial: "comments/comment_likes", locals: { comment: comment } %>
        <%= render partial: "comments/comment_on_comments_index", locals: {comment: comment } %>
        <%= render partial: "comments/comment_on_comments_new", locals: { comment: comment } %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/comments/_comments_new.html.erb
<button 
  type="button" 
  class="btn btn-dark m-1"
  data-bs-toggle="collapse"
  data-bs-target="#new-comment"
  aria-expanded="false"
  aria-controls="new-comment">
  Write a comment
</button>
<div id="new-comment" class="container card p-3 <%= ['card-bg-1', 'card-bg-2', 'card-bg-3', 'card-bg-4', 'card-bg-5'].sample %> text-dark collapse m-2">
  <h3>Comments:</h3>
  <div class="d-flex flex-column">
    <%= form_with(model: comment, url: gossip_comments_path(gossip), local: true) do |form| %>
      <%= form.hidden_field :gossip_id, value: gossip.id %>
      <%= form.label "Write your comment:", class: "form-label" %>
      <br>
      <%= form.text_area :content, class: "form-control" %>
      <br>
      <%= form.submit "Post", class:"btn btn-dark" %>
    <% end %>
  </div>
</div>

app/views/comments/edit.html.erb
<div class="d-flex flex-column w-50 m-auto text-dark">
  <h1>Edit your comment:</h1>
  <%= form_with( model: @comment, url: comment_path(@comment), local: true) do |form| %>
    <%= form.hidden_field :user_id, value: @comment.user.id %>
    <%= form.label "Write your comment:", class: "form-label" %>
    <br>
    <%= form.text_area :content, class: "form-control" %>
    <br>
    <%= form.submit "Post", class:"btn btn-dark" %>
  <% end %>
</div>