config/routes.rb
Rails.application.routes.draw do
  root 'gossip#index'

  resources :gossip do
    resources :comments, shallow: true do
      resources :comments, defaults: { commentable: 'comment' }
      resources :likes, only: [:create, :destroy], defaults: { likeable: 'comment' }
    end
    resources :likes, only: [:create, :destroy], defaults: { likeable: 'gossip' }
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :tags

  resources :users
  resources :cities, only: :show

  get '/contacts', to: 'static#contacts'
  get '/team', to: 'static#team'
  get '/welcome/:name', to: 'static#welcome'

  post '/update_location', to: 'users#update_location'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user

  belongs_to :commentable, polymorphic: true
  has_many :likes, as: :likeable
  has_many :comments, as: :commentable
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  after_create :set_location
  attr_accessor :tag_ids

  validates :title, presence: true, length: { in: 2..14 }
  validates :content, presence: true
  validates :latitude, numericality: { greater_than_or_equal_to: -90, less_than_or_equal_to: 90 }, allow_nil: true
  validates :longitude, numericality: { greater_than_or_equal_to: -180, less_than_or_equal_to: 180 }, allow_nil: true

  belongs_to :user

  has_many :gossip_tags
  has_many :tags, through: :gossip_tags

  has_many :comments, as: :commentable

  has_many :likes, as: :likeable

  def set_location
    self.longitude = user.longitude
    self.latitude = user.latitude
    save!
  end
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likeable, polymorphic: true
end

app/models/message_recipient.rb
class MessageRecipient < ApplicationRecord
  belongs_to :private_message
  belongs_to :recipient, class_name: 'User'
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  has_many :message_recipients
  has_many :recipients, through: :message_recipients
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :title, presence: true
  has_many :gossip_tags
  has_many :gossips, through: :gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true
  validates_format_of :email, with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "must be a valid email address"
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :city, presence: true
  validates :age, presence: true
  validates :description, presence: true
  validates :latitude, numericality: { greater_than_or_equal_to: -90, less_than_or_equal_to: 90 }, allow_nil: true
  validates :longitude, numericality: { greater_than_or_equal_to: -180, less_than_or_equal_to: 180 }, allow_nil: true

  belongs_to :city
  has_many :gossips

  has_many :sent_messages, class_name: 'PrivateMessage', foreign_key: 'sender_id'
  has_many :message_recipients, foreign_key: :recipient_id
  has_many :received_messages, through: :message_recipients, source: :private_message

  has_many :comments

  has_many :likes
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user
  before_action :set_likeable, only: [:create]

  def create
    @like = @likeable.likes.new(user: current_user)
    flash[:alert] = error_string(@like) unless @like.save
    redirect_back_or_to gossip_path(root_gossip_id(@like))
  end

  def destroy
    @like = Like.find(params[:id])

    flash[:alert] = error_string(@like) unless @like.destroy

    redirect_back_or_to gossip_path(root_gossip_id(@like))
  end

  private

  def root_gossip_id(like)
    like.likeable.instance_of?(Gossip) ? like.likeable.id : like.likeable.commentable.id
  end

  def set_likeable
    @likeable = params[:likeable].classify.constantize.find(params[:like][:likeable_id])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
    @gossips = @tag.gossips
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @my_gossip = @user.gossips
    @liked_gossip = @user.likes.select { |like| like.likeable_type == 'Gossip' }.map(&:likeable)
  end

  def new
    @user = User.new
    @cities = City.all
  end

  def create
    @cities = City.all
    @user = User.new(users_params)

    if @user.save
      flash[:notice] = 'Registration successful'
      log_in(@user)
      redirect_to user_path(@user)
    else
      flash.now[:alert] = error_string(@user)
      render :new
    end
  end

  def update_location
    return unless current_user

    if current_user.update(latitude: params[:user][:latitude], longitude: params[:user][:longitude])
      session[:watchId] = params[:watchId]
    else
      head :internal_server_error
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:notice] = 'User deleted successfully'
      redirect_to gossip_index_path
    else
      flash.now[:alert] = error_string(@user)
      render :show
    end
  end

  private

  def users_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :description,
      :age,
      :email,
      :password,
      :password_confirmation,
      :city_id
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def random_card_class
    ['card-bg-1', 'card-bg-2', 'card-bg-3', 'card-bg-4', 'card-bg-5'].sample
  end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/geolocation_helper.rb
# frozen_string_literal: true

module GeolocationHelper
  def within_50_meters?(point1, point2)
    if point1.latitude && point1.longitude && point2.latitude && point2.longitude
      lat1 = point1.latitude
      lon1 = point1.longitude
      lat2 = point2.latitude
      lon2 = point2.longitude

      radius_of_earth = 6371e3
      latitude1_rad = lat1 * Math::PI / 180
      latitude2_rad = lat2 * Math::PI / 180
      change_in_latitude_rad = (lat2 - lat1) * Math::PI / 180
      change_in_longitude_rad = (lon2 - lon1) * Math::PI / 180

      a = Math.sin(change_in_latitude_rad / 2)**2 +
          Math.cos(latitude1_rad) * Math.cos(latitude2_rad) *
          Math.sin(change_in_longitude_rad / 2)**2
      c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a))

      distance = radius_of_earth * c

      distance <= 50
    else
      false
    end
  end
end

app/helpers/gossip_helper.rb
module GossipHelper
  include GeolocationHelper
  def nearby_gossip
    Gossip.all.filter { |gossip| within_50_meters?(gossip, current_user) }
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def check_if_current_user(user)
    user == current_user
  end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/likes/_likes.html.erb
<div class="container d-flex flex-row m-2 justify-content-center">
  <% if gossip.likes.map(&:user).include?(current_user) %>
    <% like = gossip.likes.find_by(user: current_user) %>
    <%= form_with(model: like, url: gossip_like_path(gossip, like), method: :delete, local: true) do |form| %>
      <button name="commit" type="submit" class="btn btn-success position-relative">
        Remove Like <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill badge bg-secondary"><%= gossip.likes.count %></span>
      </button>
    <% end %>

  <% else %>
    <%= form_with(model: Like.new , url: gossip_likes_path(gossip), local: true) do |form| %>
      <%= form.hidden_field :likeable_id, value: gossip.id %>
      <button name="commit" type="submit" class="btn btn-success position-relative">
        Like <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill badge bg-secondary"><%= gossip.likes.count %></span>
      </button>
    <% end %>
  <% end %>
</div>

app/views/tags/_tags_index.html.erb
<% color_options = ['card-bg-1', 'card-bg-2', 'card-bg-3'] %>
<div class="container">
  <div class="container d-flex flex-wrap">
    <% tags.each_with_index do |tag, index| %>
      <span class="border border-dark d-inline-block <%= color_options[index % color_options.length] %> rounded-pill px-2 py-1 text-bg-light">
        <%= link_to tag.title, tag_path(tag.id), class: "link-dark"  %></span>

    <% end %>
  </div>

</div>

app/views/tags/index.html.erb
<div class="container d-flex text-dark flex-wrap">
  <h1>All Tags</h1>
  
  <%= render partial: "tags/tags_index", locals: { tags: @tags } %>
</div>

app/views/tags/show.html.erb
<div class="d-flex flex-column text-dark ">
  <div class="d-flex justify-content-center">
    <h1>Gossip from <%= @tag.title %></h1>
  </div>
  <div class="container">
    <%#= button_to 'Create User', new_user_path, method: :get, class:'btn btn-primary' %>
    
  </div>
  <div class="d-flex flex-wrap justify-content-evenly">
    <%= render partial: "gossip/index", locals: { gossips: @gossips} %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container text-dark card p-3 <%= ['card-bg-1', 'card-bg-2', 'card-bg-3', 'card-bg-4', 'card-bg-5'].sample %>">

  <h1>Register:</h1>
  <%= form_with(model: @user, url: users_path, method: :post) do |form| %>
    <div class="mb-3">
      <%= form.label :first_name %>
      <%= form.text_field :first_name, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :last_name %>
      <%= form.text_field :last_name, class: "form-control"  %>
    </div>
    <div class="mb-3">
      <%= form.label :age %>
      <%= form.text_field :age, class: "form-control"  %>
    </div>
    <div class="mb-3">
      <%= form.label :description %>
      <%= form.text_area :description, class: "form-control"  %>
    </div>
    <div class="mb-3">
      <%= form.label :city_id %>
      <%= form.select :city_id, @cities.collect {|u| [u.name, u.id]}, {prompt: "Select your city"}, {class: "form-select form-select-lg"} %>
    </div>
    <div class="mb-3">
      <%= form.label :email %>
      <%= form.text_field :email, class: "form-control"  %>
    </div>
    <div class="mb-3">
      <%= form.label :password %>
      <%= form.password_field :password, class: "form-control"  %>
    </div>
    <div class="mb-3">
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation, class: "form-control"  %>
    </div>
    <%= form.submit class:"btn btn-dark" %>
  <% end %>
  
</div>

app/views/users/show.html.erb
<div class="d-flex flex-column text-dark text-center justify-content-center align-items-center pt-5">
  <h1>This is me:</h1>
  <div class="p-5 card w-50 rounded-circle card-bg-3">
    <div class="card-body">
      <div class="d-flex justify-content-center">
        <div>
          <h3 class="card-title"><%= @user.first_name %> <%= @user.last_name %></h3>
          <h5 class="card-title">Age: <%= @user.age %></h5>
          <h5 class="card-title">Email: <%#= @user.email %></h5>
          <h5 class="card-title">City: <%= link_to @user.city.name , city_path(@user.city_id), class: "link-dark" %></h5>
          
          <p class="card-text"><%= @user.description %></p>
          <% if current_user.id == (@user.id) %>
            
            <%#= button_to "Delete user", user_path(@user.id), method: :delete, class: "btn btn-danger" %>
          <% end %>

        </div>
      </div>
    </div>
  </div>
  <div class="container d-flex flex-row justify-content-center m-5"> <% if current_user %>
      <%= button_to 'Create Gossip', new_gossip_path, method: :get, class:'btn btn-dark' %>
    <% end %>
  </div>
  <div id="user-gossip-by-user" class="container mt-5">
    <h1>My Gosip:</h1>
    <%= render partial: "gossip/index", locals: { gossips: @my_gossip} %>
  </div>
  <div id="user-liked-gossip" class="container mt-5">
    <h1>Liked Gosip:</h1>
    <%= render partial: "gossip/index", locals: { gossips: @liked_gossip} %>
  </div>
</div>