config/routes.rb
Rails.application.routes.draw do
  root 'gossip#index'

  resources :gossip do
    resources :comments, shallow: true do
      resources :comments, defaults: { commentable: 'comment' }
      resources :likes, only: [:create, :destroy], defaults: { likeable: 'comment' }
    end
    resources :likes, only: [:create, :destroy], defaults: { likeable: 'gossip' }
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :tags

  resources :users
  resources :cities, only: :show

  get '/contacts', to: 'static#contacts'
  get '/team', to: 'static#team'
  get '/welcome/:name', to: 'static#welcome'

  post '/update_location', to: 'users#update_location'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user

  belongs_to :commentable, polymorphic: true
  has_many :likes, as: :likeable
  has_many :comments, as: :commentable
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  after_create :set_location
  attr_accessor :tag_ids

  validates :title, presence: true, length: { in: 2..14 }
  validates :content, presence: true
  validates :latitude, numericality: { greater_than_or_equal_to: -90, less_than_or_equal_to: 90 }, allow_nil: true
  validates :longitude, numericality: { greater_than_or_equal_to: -180, less_than_or_equal_to: 180 }, allow_nil: true

  belongs_to :user

  has_many :gossip_tags
  has_many :tags, through: :gossip_tags

  has_many :comments, as: :commentable

  has_many :likes, as: :likeable

  def set_location
    self.longitude = user.longitude
    self.latitude = user.latitude
    save!
  end
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likeable, polymorphic: true
end

app/models/message_recipient.rb
class MessageRecipient < ApplicationRecord
  belongs_to :private_message
  belongs_to :recipient, class_name: 'User'
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  has_many :message_recipients
  has_many :recipients, through: :message_recipients
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :title, presence: true
  has_many :gossip_tags
  has_many :gossips, through: :gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true
  validates_format_of :email, with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "must be a valid email address"
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :city, presence: true
  validates :age, presence: true
  validates :description, presence: true
  validates :latitude, numericality: { greater_than_or_equal_to: -90, less_than_or_equal_to: 90 }, allow_nil: true
  validates :longitude, numericality: { greater_than_or_equal_to: -180, less_than_or_equal_to: 180 }, allow_nil: true

  belongs_to :city
  has_many :gossips

  has_many :sent_messages, class_name: 'PrivateMessage', foreign_key: 'sender_id'
  has_many :message_recipients, foreign_key: :recipient_id
  has_many :received_messages, through: :message_recipients, source: :private_message

  has_many :comments

  has_many :likes
end

app/helpers/application_helper.rb
module ApplicationHelper
  def random_card_class
    ['card-bg-1', 'card-bg-2', 'card-bg-3', 'card-bg-4', 'card-bg-5'].sample
  end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/geolocation_helper.rb
# frozen_string_literal: true

module GeolocationHelper
  def within_50_meters?(point1, point2)
    if point1.latitude && point1.longitude && point2.latitude && point2.longitude
      lat1 = point1.latitude
      lon1 = point1.longitude
      lat2 = point2.latitude
      lon2 = point2.longitude

      radius_of_earth = 6371e3
      latitude1_rad = lat1 * Math::PI / 180
      latitude2_rad = lat2 * Math::PI / 180
      change_in_latitude_rad = (lat2 - lat1) * Math::PI / 180
      change_in_longitude_rad = (lon2 - lon1) * Math::PI / 180

      a = Math.sin(change_in_latitude_rad / 2)**2 +
          Math.cos(latitude1_rad) * Math.cos(latitude2_rad) *
          Math.sin(change_in_longitude_rad / 2)**2
      c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a))

      distance = radius_of_earth * c

      distance <= 50
    else
      false
    end
  end
end

app/helpers/gossip_helper.rb
module GossipHelper
  include GeolocationHelper
  def nearby_gossip
    Gossip.all.filter { |gossip| within_50_meters?(gossip, current_user) }
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def check_if_current_user(user)
    user == current_user
  end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_alerts.html.erb
<% if flash != nil %>
    <% flash.each do |type, message| %>
      <% if type == "notice" %>
          <div class="header-alert alert alert-success alert-dismissible" role="alert">
      <% elsif type == "alert" || type == "error" %>
          <div class="header-alert alert alert-danger alert-dismissible" role="alert">
      <% elsif type == "warning" %>
          <div class="header-alert alert alert-warning alert-dismissible" role="alert">
      <% else %>
          <div class="header-alert alert alert-info alert-dismissible" role="alert">
      <% end %>
            <%=message%> 
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
    <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer id="footer">
  <hr>
  <div class="container">
    <ul class="nav nav-underline pb-3">
      <li class="nav-item">
        <%= link_to 'Home', root_path, class:["nav-link", ('active' if controller_name == 'gossip' && action_name == 'index')] %>

      </li>
      <li class="nav-item">
        <%= link_to 'Contacts', contacts_path, class:["nav-link", ('active' if action_name == 'contacts')] %>
      </li>
      <li class="nav-item">
        <%= link_to 'Team', team_path, class:["nav-link", ('active' if action_name == 'team')] %>
      </li>
    </ul>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-expand-lg ">
    <div class="container-fluid d-flex">
      <div class="navbar-nav mb-2 mb-lg-0">
        <a class="navbar-brand" href="<%= root_path %>">The Gossip Project</a>
      </div>
      <div class="navbar-nav w-50 flex-row me-auto mb-2 mb-lg-0">
        <div class="nav-item mx-2">
          <%= link_to 'Contacts', contacts_path, class:'nav-link' %>
        </div>
        <div class="nav-item mx-2">
          <%= link_to 'Team', team_path, class:'nav-link' %>
        </div>
        <% if current_user %>
          <div class="nav-item mx-2">
            <%= button_to 'Log out', session_path(session.id) , method: :delete, class:'btn btn-link nav-link' %>
          </div>
          <div class="nav-item mx-2">
            <%= link_to 'Profile', user_path(current_user), class:'nav-link' %>
          </div>
        <% else %>
          <div class="nav-item mx-2">
            <%= link_to 'Create account', new_user_path, class:'nav-link' %>
          </div>
          <div class="nav-item mx-2">
            <%= link_to 'Log in', new_session_path, class:'nav-link' %>
          </div>
        <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%#= enable bootstrap  %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <style type="text/css" media="all">
  </style>
  <body data-turbo="false" class="d-flex flex-column justify-content-between">
    <%= render "layouts/navbar" %>
    <%= render "layouts/alerts" %>
   <div class="position-relative">
    

    <%= yield %>
   </div> 

    <%= render "layouts/footer" %>
  </body>

</html>